/** ЦЕХ CORE100 — Stage 71-80 Autonomous Planning Layer.
 * Планирование и approval-gate. Никаких хозяйственных мутаций без явного approve.
 */
var STAGE71_80_LIMIT_=500;
function _ap80Scope_(r,s){return !!r&&String(r.organization_id||'')===String(s.organization_id||'')&&(!s.location_id||!r.location_id||String(r.location_id)===String(s.location_id));}
function _ap80Loc_(d,s){var l=String((d&&d.locationId)||s.location_id||'');if(l)assertLocationAllowed_(s,l,'AUTONOMOUS_PLANNING');return l;}
function _ap80Num_(v){var n=Number(v);return isFinite(n)?n:0;}
function _ap80Hash_(v){var b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v||''));return b.map(function(x){return ('0'+(x<0?x+256:x).toString(16)).slice(-2);}).join('');}
function _ap80Rows_(sheet,pred,limit){return (findRows_(sheet,pred)||[]).slice(0,limit||STAGE71_80_LIMIT_);}
function _ap80Period_(d){d=d||{};var f=String(d.dateFrom||'').slice(0,10),t=String(d.dateTo||'').slice(0,10);if(!f||!t){var now=new Date();var from=new Date(now.getTime()+86400000),to=new Date(now.getTime()+7*86400000);f=from.toISOString().slice(0,10);t=to.toISOString().slice(0,10);}if(t<f)throw new Error('Некорректный горизонт планирования.');return {from:f,to:t};}

// 71 — Autonomous Planning Run: агрегирует forecast/MRP/capacity/labor в предложения.
function runAutonomousPlanning71_(d,s){d=d||{};var l=_ap80Loc_(d,s),p=_ap80Period_(d),h=Math.max(1,Math.min(90,Number(d.horizonDays)||14));var forecast=getEnterpriseForecast69_({locationId:l,asOf:d.asOf,horizonDays:h},s);var props=[];forecast.material_requirements.lines.filter(function(x){return _ap80Num_(x.net_requirement)>0;}).slice(0,STAGE71_80_LIMIT_).forEach(function(x){props.push({type:'PROCUREMENT',entity_type:'PRODUCT',entity_id:x.product_id,qty:x.net_requirement,priority:x.net_requirement>_ap80Num_(x.gross_requirement)*.5?'HIGH':'MEDIUM',reason:'MRP_NET_REQUIREMENT'});});forecast.demand.forecast.slice(0,STAGE71_80_LIMIT_).forEach(function(x){if(_ap80Num_(x.forecast_qty)>0)props.push({type:'PRODUCTION',entity_type:'DISH',entity_id:x.dish_id,qty:x.forecast_qty,priority:'MEDIUM',reason:'DEMAND_FORECAST'});});var laborGap=forecast.labor_forecast.forecast_labor_hours; if(laborGap>0)props.push({type:'LABOR',entity_type:'CAPACITY',entity_id:'LABOR',qty:laborGap,priority:'MEDIUM',reason:'LABOR_FORECAST'});var payload={location_id:l,period:p,horizon_days:h,proposal_count:props.length,proposals:props};var run={planning_run_id:generateId_('PLANNING_RUNS'),organization_id:s.organization_id,location_id:l,date_from:p.from,date_to:p.to,horizon_days:h,status:'PROPOSED',proposal_hash:_ap80Hash_(JSON.stringify(props)),summary_json:JSON.stringify({proposal_count:props.length,labor_hours:laborGap}),created_by:s.user_id,created_at:nowIso_()};insertRow_('PLANNING_RUNS',run);props.forEach(function(x,i){insertRow_('PLANNING_PROPOSALS',{proposal_id:generateId_('PLANNING_PROPOSALS'),planning_run_id:run.planning_run_id,organization_id:s.organization_id,location_id:l,type:x.type,entity_type:x.entity_type,entity_id:x.entity_id,qty:x.qty,priority:x.priority,reason:x.reason,status:'PROPOSED',approval_gate_id:'',created_by:s.user_id,created_at:nowIso_()});});return {run:run,proposals:props};}

// 72 — Planning proposals read model.
function getPlanningProposals72_(d,s){d=d||{};var l=_ap80Loc_(d,s);return _ap80Rows_('PLANNING_PROPOSALS',function(r){return _ap80Scope_(r,{organization_id:s.organization_id,location_id:l})&&(!d.planningRunId||r.planning_run_id===d.planningRunId)&&(!d.status||r.status===d.status);},STAGE71_80_LIMIT_);}

// 73 — Approval gate. It binds exact proposal IDs and their hash.
function createPlanningApprovalGate73_(d,s){d=d||{};var l=_ap80Loc_(d,s),ids=(d.proposalIds||[]).map(String);if(!ids.length)throw new Error('proposalIds обязателен.');var rows=getPlanningProposals72_({locationId:l},s).filter(function(r){return ids.indexOf(String(r.proposal_id))>=0;});if(rows.length!==ids.length)throw new Error('Часть предложений не найдена в текущем scope.');var hash=_ap80Hash_(rows.map(function(r){return [r.proposal_id,r.type,r.entity_id,r.qty,r.priority,r.reason].join('|');}).sort().join('\n'));var gate={approval_gate_id:generateId_('APPROVAL_GATES'),organization_id:s.organization_id,location_id:l,planning_run_id:rows[0].planning_run_id,proposal_hash:hash,proposal_count:rows.length,status:'PENDING',requested_by:s.user_id,requested_at:nowIso_(),approved_by:'',approved_at:'',rejected_by:'',rejected_at:'',reason:String(d.reason||'').slice(0,1000)};insertRow_('APPROVAL_GATES',gate);rows.forEach(function(r){r.approval_gate_id=gate.approval_gate_id;updateRow_('PLANNING_PROPOSALS',r);});auditLog_(s.user_id,'Создан approval gate автономного плана','APPROVAL_GATES:'+gate.approval_gate_id,'',JSON.stringify({proposal_count:rows.length,hash:hash}),'success',s.cascade_id||'');return gate;}

function _ap80Gate_(id,s){var rows=_ap80Rows_('APPROVAL_GATES',function(r){return _ap80Scope_(r,s)&&r.approval_gate_id===id;},2);if(!rows.length)throw new Error('Approval gate не найден.');return rows[0];}

// 74 — explicit approval; no business operation is executed here.
function approvePlanningGate74_(d,s){d=d||{};var g=_ap80Gate_(String(d.approvalGateId||''),s);if(g.status!=='PENDING')throw new Error('Approval gate уже обработан.');if(String(g.requested_by)===String(s.user_id)&&String(s.role||s.роль||'').toUpperCase()!=='ADMIN')throw new Error('Нельзя утвердить собственный approval request.');var rows=getPlanningProposals72_({locationId:g.location_id,planningRunId:g.planning_run_id},s).filter(function(r){return r.approval_gate_id===g.approval_gate_id;});var hash=_ap80Hash_(rows.map(function(r){return [r.proposal_id,r.type,r.entity_id,r.qty,r.priority,r.reason].join('|');}).sort().join('\n'));if(hash!==g.proposal_hash)throw new Error('Proposal hash изменён. Требуется новый approval gate.');g.status='APPROVED';g.approved_by=s.user_id;g.approved_at=nowIso_();updateRow_('APPROVAL_GATES',g);rows.forEach(function(r){r.status='APPROVED';updateRow_('PLANNING_PROPOSALS',r);});auditLog_(s.user_id,'Утверждён approval gate автономного плана','APPROVAL_GATES:'+g.approval_gate_id,'',JSON.stringify({hash:hash}),'success',s.cascade_id||'');return g;}
function rejectPlanningGate74_(d,s){d=d||{};var g=_ap80Gate_(String(d.approvalGateId||''),s);if(g.status!=='PENDING')throw new Error('Approval gate уже обработан.');g.status='REJECTED';g.rejected_by=s.user_id;g.rejected_at=nowIso_();g.reason=String(d.reason||g.reason||'Отклонено').slice(0,1000);updateRow_('APPROVAL_GATES',g);getPlanningProposals72_({locationId:g.location_id,planningRunId:g.planning_run_id},s).filter(function(r){return r.approval_gate_id===g.approval_gate_id;}).forEach(function(r){r.status='REJECTED';updateRow_('PLANNING_PROPOSALS',r);});return g;}

// 75 — outcome registry; records fact after human/system execution elsewhere.
function recordPlanningOutcome75_(d,s){d=d||{};var l=_ap80Loc_(d,s),pid=String(d.proposalId||'');var props=getPlanningProposals72_({locationId:l},s).filter(function(r){return r.proposal_id===pid;});if(!props.length)throw new Error('Proposal не найден.');var p=props[0];if(p.status!=='APPROVED')throw new Error('Outcome разрешён только для APPROVED proposal.');var r={outcome_id:generateId_('EXECUTION_OUTCOMES'),proposal_id:pid,approval_gate_id:p.approval_gate_id,organization_id:s.organization_id,location_id:l,status:String(d.status||'EXECUTED'),actual_qty:_ap80Num_(d.actualQty),actual_cost:_ap80Num_(d.actualCost),reference_type:String(d.referenceType||''),reference_id:String(d.referenceId||''),evidence_json:JSON.stringify(d.evidence||{}),recorded_by:s.user_id,recorded_at:nowIso_()};insertRow_('EXECUTION_OUTCOMES',r);return r;}

// 76 — outcome read model.
function getPlanningOutcomes76_(d,s){d=d||{};var l=_ap80Loc_(d,s);return _ap80Rows_('EXECUTION_OUTCOMES',function(r){return _ap80Scope_(r,{organization_id:s.organization_id,location_id:l})&&(!d.proposalId||r.proposal_id===d.proposalId);},STAGE71_80_LIMIT_);}

// 77 — planning summary / variance.
function getAutonomousPlanSummary77_(d,s){d=d||{};var l=_ap80Loc_(d,s),props=getPlanningProposals72_({locationId:l,planningRunId:d.planningRunId},s),out=getPlanningOutcomes76_({locationId:l},s),approved=props.filter(function(x){return x.status==='APPROVED';}),done=out.filter(function(x){return x.status==='EXECUTED'||x.status==='COMPLETED';}),plannedQty=approved.reduce(function(a,x){return a+_ap80Num_(x.qty);},0),actualQty=done.reduce(function(a,x){return a+_ap80Num_(x.actual_qty);},0);return {location_id:l,planning_run_id:d.planningRunId||'',proposal_count:props.length,approved_count:approved.length,executed_count:done.length,planned_qty:plannedQty,actual_qty:actualQty,variance_qty:actualQty-plannedQty,status:approved.length===done.length&&approved.length?'GREEN':(approved.length?'ATTENTION':'GREEN')};}

// 78 — guard contract: proves planning layer has no direct warehouse/production/cash mutation.
function verifyAutonomousPlanningGuard78_(){var source=String(runAutonomousPlanning71_);var forbidden=['processOperation(','createWarehouse','createProduction','recordCash','postJournal'];return {simulation_only:true,forbidden_mutations:forbidden.filter(function(x){return source.indexOf(x)>=0;}),status:forbidden.some(function(x){return source.indexOf(x)>=0;})?'FAIL':'OK'};}

// 79 — operational alert from approved plans without executing them.
function getAutonomousPlanningAlerts79_(d,s){var l=_ap80Loc_(d,s),props=getPlanningProposals72_({locationId:l,status:'APPROVED'},s),out=getPlanningOutcomes76_({locationId:l},s),done={};out.forEach(function(x){done[x.proposal_id]=true;});return props.filter(function(p){return !done[p.proposal_id];}).slice(0,STAGE71_80_LIMIT_).map(function(p){return {proposal_id:p.proposal_id,type:p.type,priority:p.priority,entity_id:p.entity_id,qty:p.qty,severity:p.priority==='HIGH'?'HIGH':'MEDIUM',code:'APPROVED_PLAN_NOT_EXECUTED'};});}

// 80 — command center bridge.
function getAutonomousPlanningCommandCenter80_(d,s){d=d||{};var l=_ap80Loc_(d,s),alerts=getAutonomousPlanningAlerts79_({locationId:l},s),summary=getAutonomousPlanSummary77_({locationId:l,planningRunId:d.planningRunId},s),status=alerts.some(function(x){return x.severity==='HIGH';})?'ATTENTION':'GREEN';return {status:status,generated_at:nowIso_(),location_id:l,summary:summary,alerts:alerts.slice(0,100),approval_required:true,simulation_only:true};}

function autonomousPlanningStage71to80Trigger_(){try{getOrganizations_(null).forEach(function(org){try{(getLocations_(org.organization_id)||[]).forEach(function(loc){var s={user_id:'system',organization_id:org.organization_id,location_id:loc.location_id,role:'ADMIN',allowed_locations:[loc.location_id],cascade_id:'',operation_id:''};var cc=getAutonomousPlanningCommandCenter80_({locationId:loc.location_id},s);if(cc.status!=='GREEN')notify_(org.organization_id,loc.location_id,'AUTONOMOUS_PLANNING','Autonomous Planning: '+cc.status,'ap7180|'+loc.location_id);});}catch(e){logSystemError_('autonomousPlanningStage71to80Trigger_',org.organization_id,'autonomous_planning_71_80',e);}});}catch(e){logSystemError_('autonomousPlanningStage71to80Trigger_',null,'autonomous_planning_71_80',e);}}
function autonomousPlanningStage71to80Tests_(){var g=verifyAutonomousPlanningGuard78_();return [{name:'RUN',status:typeof runAutonomousPlanning71_==='function'?'OK':'FAIL'},{name:'PROPOSALS',status:typeof getPlanningProposals72_==='function'?'OK':'FAIL'},{name:'APPROVAL',status:typeof createPlanningApprovalGate73_==='function'&&typeof approvePlanningGate74_==='function'?'OK':'FAIL'},{name:'OUTCOME',status:typeof recordPlanningOutcome75_==='function'?'OK':'FAIL'},{name:'SUMMARY',status:typeof getAutonomousPlanSummary77_==='function'?'OK':'FAIL'},{name:'GUARD',status:g.status},{name:'NO_AUTO_MUTATION',status:g.simulation_only&&g.forbidden_mutations.length===0?'OK':'FAIL'},{name:'COMMAND',status:typeof getAutonomousPlanningCommandCenter80_==='function'?'OK':'FAIL'}];}
