// Stage 38 static/contract tests. Full Google Sheets runtime requires Apps Script deployment.
function complianceMatrixStage38ContractTests_(){
  var r=[];function t(name,ok){r.push({name:name,status:ok?'OK':'FAIL'});}
  t('SCHEMA_CONTROLS',Array.isArray(CONFIG.SCHEMA.COMPLIANCE_CONTROLS));
  t('SCHEMA_LINKS',Array.isArray(CONFIG.SCHEMA.COMPLIANCE_CONTROL_LINKS));
  t('SHEETS_CONTROLS',CONFIG.SHEETS.COMPLIANCE_CONTROLS==='COMPLIANCE_CONTROLS');
  t('SHEETS_LINKS',CONFIG.SHEETS.COMPLIANCE_CONTROL_LINKS==='COMPLIANCE_CONTROL_LINKS');
  t('IDS',CONFIG.ID_PREFIXES.COMPLIANCE_CONTROLS==='CTRL'&&CONFIG.ID_PREFIXES.COMPLIANCE_CONTROL_LINKS==='CLNK');
  t('API_READ',CONFIG.ACTION_MODULE.GET_COMPLIANCE_MATRIX==='dashboard'&&CONFIG.ACTION_MODULE.GET_COMPLIANCE_CONTROLS==='dashboard');
  t('API_WRITE',CONFIG.ACTION_MODULE.CREATE_COMPLIANCE_CONTROL==='audit_admin'&&CONFIG.ACTION_MODULE.LINK_COMPLIANCE_CONTROL==='audit_admin');
  t('BOUNDED',CM38_LIMIT_===500);
  t('SEED',_cm38Seed_().length===9);
  return r;
}
