/** ЦЕХ — Stage 31 Data Quality & Reconciliation Engine. Read-only diagnostics + safe reconcile queue. */
var DQ31_LIMIT_=200;
function _dq31Num_(v){var n=Number(v);return isFinite(n)?n:0;}
function _dq31Issue_(code,severity,entityType,entityId,message,details){return {issue_id:generateId_('DATA_QUALITY_ISSUES'),code:code,severity:severity,entity_type:entityType,entity_id:entityId,message:message,details:details||{},status:'OPEN'};}
function _dq31Owned_(r,s){return r&&r.organization_id===s.organization_id&&(!r.location_id||!s.location_id||r.location_id===s.location_id);}
function _dq31Rows_(sheet,fn){return findRows_(sheet,fn||function(){return true;});}
function runDataQualityAudit_(data,session){
  data=data||{}; var issues=[], products=_dq31Rows_('PRODUCTS',function(r){return r.organization_id===session.organization_id&&(!session.location_id||r.location_id===session.location_id);});
  var productIds={}; products.forEach(function(p){productIds[p.product_id]=1;if(!String(p.название||'').trim()) issues.push(_dq31Issue_('PRODUCT_NAME_MISSING','HIGH','PRODUCT',p.product_id,'У продукта отсутствует название.'));});
  var batches=_dq31Rows_('BATCHES',function(r){return r.organization_id===session.organization_id&&(!session.location_id||r.location_id===session.location_id);});
  batches.forEach(function(b){if(!productIds[b.product_id]) issues.push(_dq31Issue_('BATCH_PRODUCT_LINK','CRITICAL','BATCH',b.batch_id,'Партия ссылается на отсутствующий продукт.',{product_id:b.product_id})); if(_dq31Num_(b.количество)<0) issues.push(_dq31Issue_('NEGATIVE_BATCH_QTY','CRITICAL','BATCH',b.batch_id,'Отрицательное количество партии.',{quantity:b.количество}));});
  var recipes=_dq31Rows_('RECIPES',function(r){return !r.organization_id||r.organization_id===session.organization_id;});
  recipes.forEach(function(r){if(r.parent_id&&!productIds[r.parent_id]&&!findOne_('DISHES','dish_id',r.parent_id)&&!findOne_('SEMI_FINISHED','pf_id',r.parent_id)) issues.push(_dq31Issue_('RECIPE_PARENT_LINK','HIGH','RECIPE',r.recipe_id||r.id||'', 'ТТК/рецептура ссылается на отсутствующий объект.',{parent_id:r.parent_id}));});
  var sales=_dq31Rows_('SALES',function(r){return r.organization_id===session.organization_id&&(!session.location_id||r.location_id===session.location_id);});
  sales.forEach(function(x){if(x.dish_id&&!findOne_('DISHES','dish_id',x.dish_id)) issues.push(_dq31Issue_('SALE_DISH_LINK','HIGH','SALE',x.sale_id,'Продажа ссылается на отсутствующее блюдо.',{dish_id:x.dish_id})); if(_dq31Num_(x.qty)<0) issues.push(_dq31Issue_('NEGATIVE_SALE_QTY','CRITICAL','SALE',x.sale_id,'Отрицательное количество в продаже.',{qty:x.qty}));});
  var ops=_dq31Rows_('WAREHOUSE_OPS',function(r){return r.organization_id===session.organization_id&&(!session.location_id||r.location_id===session.location_id);});
  ops.forEach(function(o){if(o.batch_id&&!findOne_('BATCHES','batch_id',o.batch_id)) issues.push(_dq31Issue_('WAREHOUSE_BATCH_LINK','CRITICAL','WAREHOUSE_OP',o.operation_id||o.id||'','Складская операция ссылается на отсутствующую партию.',{batch_id:o.batch_id}));});
  var seen={}; products.forEach(function(p){var k=String(p.название||p.name||'').toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ').trim();if(!k)return;if(seen[k])issues.push(_dq31Issue_('PRODUCT_DUPLICATE_CANDIDATE','MEDIUM','PRODUCT',p.product_id,'Возможный дубль продукта.',{candidate_id:seen[k],normalized_name:k}));else seen[k]=p.product_id;});
  return {generated_at:nowIso_(),organization_id:session.organization_id,location_id:session.location_id||'',summary:{total:issues.length,critical:issues.filter(function(x){return x.severity==='CRITICAL';}).length,high:issues.filter(function(x){return x.severity==='HIGH';}).length,medium:issues.filter(function(x){return x.severity==='MEDIUM';}).length},issues:issues.slice(0,DQ31_LIMIT_)};
}
function getDataQualityIssues_(data,session){var r=runDataQualityAudit_(data,session);if(data&&data.severity)r.issues=r.issues.filter(function(x){return x.severity===data.severity;});return r;}
function createReconciliationCase_(data,session){if(!data||!data.issueCode)throw new Error('issueCode обязателен.');var row={reconciliation_id:generateId_('DATA_RECONCILIATIONS'),organization_id:session.organization_id,location_id:session.location_id||'',issue_code:String(data.issueCode),entity_type:String(data.entityType||''),entity_id:String(data.entityId||''),action:String(data.action||'REVIEW'),status:'PENDING_REVIEW',reason:String(data.reason||''),created_by:session.user_id,created_at:nowIso_(),resolved_by:'',resolved_at:'',resolution_json:'{}'};insertRow_('DATA_RECONCILIATIONS',row);auditLog_(session.user_id,'Создан кейс сверки данных','DATA_RECONCILIATIONS:'+row.reconciliation_id,null,row.issue_code,'success',session.cascade_id||'');return row;}
function resolveReconciliationCase_(data,session){var r=findOne_('DATA_RECONCILIATIONS','reconciliation_id',data.reconciliationId);if(!r||r.organization_id!==session.organization_id)throw new Error('Кейс сверки не найден.');if(r.status!=='PENDING_REVIEW')throw new Error('Кейс уже обработан.');updateRow_('DATA_RECONCILIATIONS',r,{status:'RESOLVED',resolved_by:session.user_id,resolved_at:nowIso_(),resolution_json:JSON.stringify(data.resolution||{})});auditLog_(session.user_id,'Закрыт кейс сверки данных','DATA_RECONCILIATIONS:'+r.reconciliation_id,r.status,'RESOLVED','success',session.cascade_id||'');return findOne_('DATA_RECONCILIATIONS','reconciliation_id',r.reconciliation_id);}
function getReconciliationCases_(data,session){return _dq31Rows_('DATA_RECONCILIATIONS',function(r){return r.organization_id===session.organization_id&&(!session.location_id||!r.location_id||r.location_id===session.location_id)&&(!data||!data.status||r.status===data.status);}).slice(0,DQ31_LIMIT_);}
function dataQualityStage31Tests_(){var o=[];function ok(n,c){o.push({name:n,status:c?'OK':'FAIL'});}ok('API',typeof runDataQualityAudit_==='function'&&typeof createReconciliationCase_==='function'&&typeof resolveReconciliationCase_==='function');ok('LIMIT',DQ31_LIMIT_===200);ok('SCHEMA',Array.isArray(CONFIG.SCHEMA.DATA_RECONCILIATIONS));ok('SHEET',CONFIG.SHEETS.DATA_RECONCILIATIONS==='DATA_RECONCILIATIONS');ok('ID',CONFIG.ID_PREFIXES.DATA_RECONCILIATIONS==='DQR');ok('RBAC',CONFIG.ACTION_MODULE.RUN_DATA_QUALITY_AUDIT==='dashboard'&&CONFIG.ACTION_MODULE.CREATE_RECONCILIATION_CASE==='master_data_admin');return o;}
