/**
 * CORE100 Stage 61-70 — Commercial Intelligence, Demand Sensing & MRP Layer.
 * Read-only analytics + explicit planning snapshots. No automatic postings.
 */
var STAGE61_70_LIMIT_ = 500;
function _ciRows_(sheet,predicate,limit){var rows=getSheetData_(sheet)||[],out=[];for(var i=0;i<rows.length&&out.length<(limit||STAGE61_70_LIMIT_);i++){if(!predicate||predicate(rows[i]))out.push(rows[i]);}return out;}
function _ciScope_(r,s){return String(r.organization_id||'')===String(s.organization_id||'')&&(!r.location_id||!s.location_id||String(r.location_id)===String(s.location_id));}
function _ciLoc_(d,s){return String((d&&d.locationId)||s.location_id||'');}
function _ciNum_(v){var n=Number(v);return isFinite(n)?n:0;}
function _ciDate_(v){return String(v||new Date().toISOString().slice(0,10)).slice(0,10);}
function _ciId_(p){return generateId_(p);}
function _ciDaysBack_(date,n){var d=new Date((date||new Date().toISOString().slice(0,10))+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-n);return d.toISOString().slice(0,10);}
function _ciChannel_(r){var x=String(r.канал||r.channel||r.source||r.источник||'DIRECT').toUpperCase();if(x.indexOf('IIKO')>=0)return 'DELIVERY/POS';if(x.indexOf('DELIVERY')>=0)return 'DELIVERY';if(x.indexOf('POS')>=0)return 'POS';return x||'DIRECT';}

// 61 — Customer / Sales Intelligence
function getCustomerSalesIntelligence61_(d,s){d=d||{};var loc=_ciLoc_(d,s),from=_ciDate_(d.dateFrom||_ciDaysBack_(d.dateTo||new Date().toISOString().slice(0,10),30)),to=_ciDate_(d.dateTo),rows=_ciRows_('SALES',function(r){var dt=String(r.дата||'').slice(0,10);return _ciScope_(r,{organization_id:s.organization_id,location_id:loc})&&dt>=from&&dt<=to;});var by={};rows.forEach(function(r){var c=_ciChannel_(r),x=by[c]||(by[c]={channel:c,orders:0,qty:0,revenue:0,cost:0});x.orders++;x.qty+=_ciNum_(r.qty);x.revenue+=_ciNum_(r.сумма)||_ciNum_(r.qty)*_ciNum_(r.цена_продажи);x.cost+=_ciNum_(r.фактическая_себестоимость_сырья)||_ciNum_(r.себестоимость_на_момент)*_ciNum_(r.qty);});return {date_from:from,date_to:to,channels:Object.keys(by).map(function(k){var x=by[k];x.gross_margin=x.revenue-x.cost;x.margin_pct=x.revenue?x.gross_margin/x.revenue*100:0;return x;})};}

// 62 — Demand sensing
function runDemandSensing62_(d,s){d=d||{};var persist=d.persist!==false;var loc=_ciLoc_(d,s),asOf=_ciDate_(d.asOf),horizon=Math.max(1,Math.min(90,Number(d.horizonDays)||14)),rows=_ciRows_('SALES',function(r){return _ciScope_(r,{organization_id:s.organization_id,location_id:loc})&&String(r.дата||'').slice(0,10)<=asOf&&String(r.дата||'').slice(0,10)>=_ciDaysBack_(asOf,56);});var by={};rows.forEach(function(r){var k=String(r.dish_id||'UNASSIGNED');if(!by[k])by[k]={dish_id:k,qty_7:0,qty_28:0,qty_56:0};var dt=String(r.дата||'').slice(0,10),q=_ciNum_(r.qty);if(dt>=_ciDaysBack_(asOf,6))by[k].qty_7+=q;if(dt>=_ciDaysBack_(asOf,27))by[k].qty_28+=q;by[k].qty_56+=q;});var forecast=Object.keys(by).map(function(k){var x=by[k],daily7=x.qty_7/7,daily28=x.qty_28/28,daily56=x.qty_56/56,base=daily7*.5+daily28*.3+daily56*.2;return {dish_id:k,daily_forecast:base,forecast_qty:base*horizon,horizon_days:horizon,method:'WEIGHTED_7_28_56'};});var plan={demand_sensing_id:_ciId_('DSEN'),organization_id:s.organization_id,location_id:loc,as_of:asOf,horizon_days:horizon,status:'CALCULATED',forecast_json:JSON.stringify(forecast.slice(0,500)),created_by:s.user_id,created_at:nowIso_()};if(persist)insertRow_('DEMAND_SENSING_PLANS',plan);return {plan:plan,forecast:forecast};}

// 63 — Procurement forecast / MRP
function runMaterialRequirements63_(d,s){d=d||{};var persist=d.persist!==false;var loc=_ciLoc_(d,s),forecast=runDemandSensing62_({locationId:loc,asOf:d.asOf,horizonDays:d.horizonDays,persist:persist},s),recipes=_ciRows_('RECIPES',function(r){return !r.parent_type||String(r.parent_type).toUpperCase()==='DISH';}),stock=_ciRows_('BATCHES',function(r){return _ciScope_(r,{organization_id:s.organization_id,location_id:loc})&&String(r.status||'').toUpperCase()!=='BLOCKED';}),stockBy={};stock.forEach(function(r){var p=String(r.product_id||'');stockBy[p]=(stockBy[p]||0)+Math.max(0,_ciNum_(r.количество));});var need={};forecast.forecast.forEach(function(f){recipes.filter(function(r){return String(r.parent_id)===String(f.dish_id);}).forEach(function(r){var p=String(r.product_id||'');need[p]=(need[p]||0)+_ciNum_(r.нетто||r.брутто)*f.forecast_qty;});});var lines=Object.keys(need).map(function(p){var n=need[p],st=stockBy[p]||0;return {product_id:p,gross_requirement:n,usable_stock:st,net_requirement:Math.max(0,n-st),coverage_ratio:n?st/n:1};});var run={mrp_run_id:_ciId_('MRP'),organization_id:s.organization_id,location_id:loc,as_of:_ciDate_(d.asOf),horizon_days:Number(d.horizonDays)||14,status:'CALCULATED',lines_json:JSON.stringify(lines.slice(0,500)),created_by:s.user_id,created_at:nowIso_()};if(persist)insertRow_('MRP_RUNS',run);return {run:run,lines:lines};}

// 64 — Cost-to-serve by channel
function getCostToServe64_(d,s){var base=getCustomerSalesIntelligence61_(d,s);return base.channels.map(function(x){var service_cost=_ciNum_(d.channelServiceCost&&d.channelServiceCost[x.channel]);x.service_cost=service_cost;x.contribution=x.gross_margin-service_cost;x.contribution_pct=x.revenue?x.contribution/x.revenue*100:0;return x;});}

// 65 — Margin by channel / commercial mix
function getChannelMargin65_(d,s){var rows=getCostToServe64_(d,s),total=rows.reduce(function(a,x){return a+x.revenue;},0);return rows.map(function(x){x.revenue_share=total?x.revenue/total*100:0;return x;}).sort(function(a,b){return b.contribution-a.contribution;});}

// 66 — Dynamic menu signals (no automatic price changes)
function getDynamicMenuSignals66_(d,s){var loc=_ciLoc_(d,s),sales=_ciRows_('SALES',function(r){return _ciScope_(r,{organization_id:s.organization_id,location_id:loc});}),dishes=_ciRows_('DISHES',function(r){return String(r.organization_id)===String(s.organization_id);}),by={};sales.forEach(function(r){var k=String(r.dish_id||'');if(!by[k])by[k]={dish_id:k,qty:0,revenue:0};by[k].qty+=_ciNum_(r.qty);by[k].revenue+=_ciNum_(r.сумма)||_ciNum_(r.qty)*_ciNum_(r.цена_продажи);});return dishes.map(function(dish){var x=by[dish.dish_id]||{qty:0,revenue:0};var margin=_ciNum_(dish.цена_продажи)-_ciNum_(dish.себестоимость);return {dish_id:dish.dish_id,name:dish.название,qty:x.qty,revenue:x.revenue,unit_margin:margin,margin_pct:_ciNum_(dish.цена_продажи)?margin/_ciNum_(dish.цена_продажи)*100:0,signal:x.qty===0?'LOW_DEMAND':(margin<0?'NEGATIVE_MARGIN':'NORMAL')};});}

// 67 — Labor demand forecast from demand sensing
function getLaborForecast67_(d,s){var loc=_ciLoc_(d,s),ds=runDemandSensing62_({locationId:loc,asOf:d.asOf,horizonDays:d.horizonDays||14,persist:false},s),hoursPerUnit=Math.max(0,Number(d.hoursPerUnit)||0);var qty=ds.forecast.reduce(function(a,x){return a+x.forecast_qty;},0);return {horizon_days:ds.plan.horizon_days,forecast_output_qty:qty,hours_per_unit:hoursPerUnit,forecast_labor_hours:qty*hoursPerUnit,source_plan_id:ds.plan.demand_sensing_id};}

// 68 — Procurement forecast bridge
function getProcurementForecast68_(d,s){d=d||{};d.persist=false;var mrp=runMaterialRequirements63_(d,s);return {mrp_run_id:mrp.run.mrp_run_id,as_of:mrp.run.as_of,horizon_days:mrp.run.horizon_days,items:mrp.lines.filter(function(x){return x.net_requirement>0;}).sort(function(a,b){return b.net_requirement-a.net_requirement;}).slice(0,500)};}

// 69 — Enterprise forecast snapshot
function getEnterpriseForecast69_(d,s){d=d||{};var loc=_ciLoc_(d,s),ds=runDemandSensing62_({locationId:loc,asOf:d.asOf,horizonDays:d.horizonDays||14,persist:false},s),mrp=runMaterialRequirements63_({locationId:loc,asOf:d.asOf,horizonDays:d.horizonDays||14,persist:false},s),labor=getLaborForecast67_({locationId:loc,asOf:d.asOf,horizonDays:d.horizonDays||14,hoursPerUnit:d.hoursPerUnit},s),menu=getDynamicMenuSignals66_({locationId:loc},s);return {generated_at:nowIso_(),location_id:loc,demand:ds,material_requirements:mrp,labor_forecast:labor,menu_signals:menu.slice(0,200)};}

// 70 — Digital Twin 2.0 / enterprise intelligence command
function getDigitalTwinV270_(d,s){d=d||{};var loc=_ciLoc_(d,s),forecast=getEnterpriseForecast69_(d,s),base=getDigitalFactoryCommandCenter60_({locationId:loc,date:d.date,dateFrom:d.dateFrom,dateTo:d.dateTo},s),alerts=[];if(forecast.material_requirements.lines.some(function(x){return x.net_requirement>0;}))alerts.push({code:'MRP_NET_REQUIREMENT',severity:'HIGH',message:'Обнаружена потребность в закупке/пополнении.',count:forecast.material_requirements.lines.filter(function(x){return x.net_requirement>0;}).length});if(forecast.menu_signals.some(function(x){return x.signal==='NEGATIVE_MARGIN';}))alerts.push({code:'NEGATIVE_MENU_MARGIN',severity:'HIGH',message:'Обнаружены блюда с отрицательной unit margin.'});var status=base.status==='BLOCKED'||alerts.some(function(a){return a.severity==='CRITICAL';})?'BLOCKED':(base.status==='ATTENTION'||alerts.length?'ATTENTION':'GREEN');return {status:status,generated_at:nowIso_(),location_id:loc,base_command_center:base,forecast:forecast,alerts:alerts};}

function digitalIntelligenceStage61to70Trigger_(){try{getOrganizations_(null).forEach(function(org){try{(getLocations_(org.organization_id)||[]).forEach(function(loc){var s={user_id:'system',organization_id:org.organization_id,location_id:loc.location_id,role:'ADMIN',allowed_locations:[loc.location_id],cascade_id:'',operation_id:''};var twin=getDigitalTwinV270_({locationId:loc.location_id},s);if(twin.status!=='GREEN')notify_(org.organization_id,loc.location_id,'DIGITAL_TWIN_V2','Digital Intelligence: '+twin.status,'di6170|'+loc.location_id);});}catch(e){logSystemError_('digitalIntelligenceStage61to70Trigger_',org.organization_id,'digital_intelligence_61_70',e);}});}catch(e){logSystemError_('digitalIntelligenceStage61to70Trigger_',null,'digital_intelligence_61_70',e);}}
