/** ЦЕХ CORE100 — Stage 42-50 Enterprise Execution Suite. */
var STAGE42_LIMIT_=500;
var STAGE43_LIMIT_=500;
var STAGE44_LIMIT_=500;
var STAGE45_LIMIT_=500;
var STAGE46_LIMIT_=500;
var STAGE47_LIMIT_=500;
var STAGE48_LIMIT_=500;
var STAGE49_LIMIT_=500;
var STAGE50_LIMIT_=500;
function _esScope_(r,s){return !!r&&r.organization_id===s.organization_id&&(!s.location_id||!r.location_id||r.location_id===s.location_id);}
function _esLoc_(data,s){var l=data&& (data.locationId||data.location_id) || s.location_id||'';if(l)assertLocationAllowed_(s,l,'ENTERPRISE_SCOPE');return l;}
function _esDate_(v){return String(v||'').slice(0,10);}
function _esNum_(v){var n=Number(v);return isFinite(n)?n:0;}
function _esRows_(sheet,fn,limit){return findRows_(sheet,fn).slice(0,limit||500);}
function _esPeriod_(data){var f=_esDate_(data&&data.dateFrom),t=_esDate_(data&&data.dateTo);if(f||t){if(!f||!t||t<f)throw new Error('Некорректный период.');return {from:f,to:t};}var d=new Date();d.setUTCDate(1);d.setUTCDate(d.getUTCDate()-1);var to=d.toISOString().slice(0,10);d.setUTCDate(1);return {from:d.toISOString().slice(0,10),to:to};}

// Stage 42 — единый backlog управленческих действий.
function createManagementAction_(data,s){data=data||{};var l=_esLoc_(data,s);if(!data.title)throw new Error('title обязателен.');var r={action_id:generateId_('MANAGEMENT_ACTION_BACKLOG'),organization_id:s.organization_id,location_id:l,source_type:String(data.sourceType||'MANUAL'),source_id:String(data.sourceId||''),title:String(data.title).slice(0,200),description:String(data.description||'').slice(0,2000),priority:String(data.priority||'MEDIUM'),status:'OPEN',owner_role:String(data.ownerRole||'ДИРЕКТОР'),owner_id:String(data.ownerId||''),due_at:String(data.dueAt||''),dependency_json:JSON.stringify(data.dependencies||[]),evidence_json:'',created_by:s.user_id,created_at:nowIso_(),completed_by:'',completed_at:'',updated_at:nowIso_()};insertRow_('MANAGEMENT_ACTION_BACKLOG',r);auditLog_(s.user_id,'Создано management action','MANAGEMENT_ACTIONS:'+r.action_id,'',JSON.stringify(r),'success',s.cascade_id||'');return r;}
function getManagementActions42_(data,s){data=data||{};var l=_esLoc_(data,s);return _esRows_('MANAGEMENT_ACTION_BACKLOG',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&(!data.status||r.status===data.status)&&(!data.priority||r.priority===data.priority)&&(!data.sourceType||r.source_type===data.sourceType);},STAGE42_LIMIT_);}
function completeManagementAction_(data,s){data=data||{};var rows=getManagementActions42_({locationId:data.locationId||s.location_id},s).filter(function(r){return r.action_id===data.actionId;});if(!rows.length)throw new Error('Management action не найден.');var r=rows[0];r.status='CLOSED';r.completed_by=s.user_id;r.completed_at=nowIso_();r.evidence_json=JSON.stringify(data.evidence||{});r.updated_at=nowIso_();updateRow_('MANAGEMENT_ACTION_BACKLOG',r);auditLog_(s.user_id,'Закрыто management action','MANAGEMENT_ACTIONS:'+r.action_id,'',JSON.stringify(data.evidence||{}),'success',s.cascade_id||'');return r;}
function orchestrateManagementActions42_(data,s){data=data||{};var l=_esLoc_(data,s),created=[];var vars=getKpiVariances_({locationId:l,status:'OFF_TARGET',limit:STAGE42_LIMIT_},s);vars.forEach(function(v){var exists=_esRows_('MANAGEMENT_ACTION_BACKLOG',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&r.source_type==='KPI_VARIANCE'&&r.source_id===v.variance_id&&r.status!=='CLOSED';},2);if(!exists.length)created.push(createManagementAction_({locationId:l,sourceType:'KPI_VARIANCE',sourceId:v.variance_id,title:'Исправить отклонение KPI '+v.metric_code,description:'Факт '+v.actual_value+' против target '+v.target_value,priority:'HIGH',ownerRole:'ДИРЕКТОР'},s));});return {created:created,count:created.length};}

// Stage 43 — планирование персонала и трудовой мощности.
function createWorkforcePlan_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data);var r={plan_id:generateId_('WORKFORCE_PLANS'),organization_id:s.organization_id,location_id:l,date_from:p.from,date_to:p.to,workshop_id:String(data.workshopId||''),required_hours:_esNum_(data.requiredHours),planned_hours:_esNum_(data.plannedHours),hourly_cost:_esNum_(data.hourlyCost),status:'DRAFT',owner_id:String(data.ownerId||''),created_by:s.user_id,created_at:nowIso_(),updated_at:nowIso_()};if(r.required_hours<0||r.planned_hours<0)throw new Error('Часы не могут быть отрицательными.');insertRow_('WORKFORCE_PLANS',r);return r;}
function getWorkforcePlans_(data,s){data=data||{};var l=_esLoc_(data,s);return _esRows_('WORKFORCE_PLANS',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&(!data.status||r.status===data.status);},STAGE43_LIMIT_);}
function getWorkforceCapacity_(data,s){var l=_esLoc_(data,s),plans=getWorkforcePlans_({locationId:l},s),totalReq=0,totalPlan=0,cost=0;plans.forEach(function(r){totalReq+=_esNum_(r.required_hours);totalPlan+=_esNum_(r.planned_hours);cost+=_esNum_(r.planned_hours)*_esNum_(r.hourly_cost);});return {location_id:l,required_hours:totalReq,planned_hours:totalPlan,gap_hours:totalPlan-totalReq,planned_labor_cost:cost,status:totalPlan>=totalReq?'GREEN':'ATTENTION'};}

// Stage 44 — scorecard поставщиков.
function runSupplierScorecards_(data,s){var l=_esLoc_(data,s),p=_esPeriod_(data),suppliers=_esRows_('SUPPLIERS',function(r){return !r.organization_id||r.organization_id===s.organization_id;},STAGE44_LIMIT_),reqs=_esRows_('PURCHASE_REQUESTS',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l});},STAGE44_LIMIT_),out=[];suppliers.forEach(function(sp){var sid=sp.supplier_id||sp.id, rows=reqs.filter(function(r){return String(r.supplier_id||'')===String(sid);}),open=rows.filter(function(r){return !['CLOSED','COMPLETED','RECEIVED'].includes(String(r.status||'').toUpperCase());}).length,score=rows.length?Math.max(0,100-rows.filter(function(r){return String(r.status||'').toUpperCase()==='CANCELLED';}).length/rows.length*100):null;var status=score===null?'NO_DATA':(score<70?'ATTENTION':'OK');var existing=_esRows_('SUPPLIER_SCORECARDS',function(x){return _esScope_(x,{organization_id:s.organization_id,location_id:l})&&x.supplier_id===sid&&x.period_from===p.from&&x.period_to===p.to;},1);var r={scorecard_id:existing.length?existing[0].scorecard_id:generateId_('SUPPLIER_SCORECARDS'),organization_id:s.organization_id,location_id:l,supplier_id:sid,period_from:p.from,period_to:p.to,request_count:rows.length,open_request_count:open,score:score,status:status,generated_at:nowIso_()};if(existing.length)updateRow_('SUPPLIER_SCORECARDS',r);else insertRow_('SUPPLIER_SCORECARDS',r);out.push({supplier_id:sid,name:sp.название||sp.name||'',requests:rows.length,open_requests:open,score:score,status:status});});return {period:p,location_id:l,items:out};}
function createProcurementAction_(data,s){data=data||{};return createManagementAction_({locationId:data.locationId||s.location_id,sourceType:'SUPPLIER_SCORECARD',sourceId:data.supplierId||'',title:data.title||'Действие по поставщику',description:data.description||'',priority:data.priority||'MEDIUM',ownerRole:data.ownerRole||'МЕНЕДЖЕР',dueAt:data.dueAt||''},s);}

// Stage 45 — политика запасов и FEFO signals.
function createInventoryPolicy_(data,s){data=data||{};var l=_esLoc_(data,s);if(!data.productId)throw new Error('productId обязателен.');var r={policy_id:generateId_('INVENTORY_POLICIES'),organization_id:s.organization_id,location_id:l,product_id:data.productId,min_qty:_esNum_(data.minQty),max_qty:_esNum_(data.maxQty),safety_qty:_esNum_(data.safetyQty),fefo_required:data.fefoRequired===false?'NO':'YES',expiry_warning_days:Number(data.expiryWarningDays||3),status:'ACTIVE',created_by:s.user_id,created_at:nowIso_(),updated_at:nowIso_()};if(r.max_qty<r.min_qty)throw new Error('max_qty меньше min_qty.');insertRow_('INVENTORY_POLICIES',r);return r;}
function getInventorySignals_(data,s){var l=_esLoc_(data||{},s),pol=_esRows_('INVENTORY_POLICIES',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&r.status==='ACTIVE';},STAGE45_LIMIT_),batches=_esRows_('BATCHES',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l});},STAGE45_LIMIT_),out=[];pol.forEach(function(p){var bs=batches.filter(function(b){return String(b.product_id||'')===String(p.product_id);}),qty=bs.reduce(function(a,b){return a+_esNum_(b.количество||b.quantity||b.qty);},0),soon=bs.filter(function(b){var e=String(b.срок_годности||b.expiry_date||'');return e&&e<=new Date(Date.now()+_esNum_(p.expiry_warning_days)*86400000).toISOString().slice(0,10);}).length;var status=qty<_esNum_(p.min_qty)?'SHORTAGE':(soon?'EXPIRY_WARNING':(qty>_esNum_(p.max_qty)&&p.max_qty>0?'OVERSTOCK':'OK'));out.push({product_id:p.product_id,quantity:qty,min_qty:p.min_qty,max_qty:p.max_qty,expiry_batches:soon,status:status});});return {location_id:l,items:out};}

// Stage 46 — производственная мощность и планирование.
function createCapacityPlan_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data);var r={capacity_plan_id:generateId_('CAPACITY_PLANS'),organization_id:s.organization_id,location_id:l,date_from:p.from,date_to:p.to,workshop_id:String(data.workshopId||''),available_hours:_esNum_(data.availableHours),planned_hours:_esNum_(data.plannedHours),planned_qty:_esNum_(data.plannedQty),status:'DRAFT',created_by:s.user_id,created_at:nowIso_(),updated_at:nowIso_()};insertRow_('CAPACITY_PLANS',r);return r;}
function getCapacityOverview_(data,s){var l=_esLoc_(data||{},s),rows=_esRows_('CAPACITY_PLANS',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l});},STAGE46_LIMIT_);var a=0,p=0,q=0;rows.forEach(function(r){a+=_esNum_(r.available_hours);p+=_esNum_(r.planned_hours);q+=_esNum_(r.planned_qty);});return {location_id:l,available_hours:a,planned_hours:p,utilization_pct:a?p/a*100:0,planned_qty:q,status:p<=a?'GREEN':'BLOCKED'};}

// Stage 47 — menu engineering / margin matrix.
function getMenuEngineering_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data),sales=_esRows_('SALES',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&String(r.дата||r.date||'').slice(0,10)>=p.from&&String(r.дата||r.date||'').slice(0,10)<=p.to;},STAGE47_LIMIT_),agg={};sales.forEach(function(r){var id=r.dish_id||'';if(!agg[id])agg[id]={dish_id:id,qty:0,revenue:0,cost:0};agg[id].qty+=_esNum_(r.qty);agg[id].revenue+=_esNum_(r.сумма);agg[id].cost+=_esNum_(r.фактическая_себестоимость_сырья||r.себестоимость_на_момент);});return {period:p,location_id:l,items:Object.keys(agg).map(function(k){var x=agg[k];x.margin=x.revenue-x.cost;x.margin_pct=x.revenue?x.margin/x.revenue*100:0;return x;}).sort(function(a,b){return b.margin-a.margin;})};}

// Stage 48 — scenario planning / what-if.
function createScenarioPlan_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data);var r={scenario_id:generateId_('SCENARIOS'),organization_id:s.organization_id,location_id:l,name:String(data.name||'Сценарий').slice(0,200),date_from:p.from,date_to:p.to,status:'DRAFT',assumptions_json:JSON.stringify(data.assumptions||{}),created_by:s.user_id,created_at:nowIso_(),updated_at:nowIso_()};insertRow_('SCENARIOS',r);return r;}
function runScenario_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data),bp=getEnterpriseBoardPack_({locationId:l,dateFrom:p.from,dateTo:p.to},s).pack,a=data.assumptions||{},rev=_esNum_(bp.headline&&bp.headline.revenue),marginPct=_esNum_(bp.headline&&bp.headline.gross_margin_pct),gross=rev*marginPct/100,baseCogs=rev-gross,revenueFactor=1+_esNum_(a.revenue_delta_pct)/100,costFactor=1+_esNum_(a.cost_delta_pct)/100,scenarioRevenue=rev*revenueFactor,scenarioCogs=baseCogs*costFactor,scenarioGross=scenarioRevenue-scenarioCogs;return {period:p,baseline_revenue:rev,scenario_revenue:scenarioRevenue,baseline_gross_profit:gross,scenario_gross_profit:scenarioGross,assumptions:a};}

// Stage 49 — единый execution plan.
function createExecutionPlan_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data),r={execution_plan_id:generateId_('EXECUTION_PLANS'),organization_id:s.organization_id,location_id:l,date_from:p.from,date_to:p.to,name:String(data.name||'Операционный план').slice(0,200),status:'DRAFT',owner_id:String(data.ownerId||''),created_by:s.user_id,created_at:nowIso_(),updated_at:nowIso_()};insertRow_('EXECUTION_PLANS',r);return r;}
function addExecutionItem_(data,s){data=data||{};if(!data.planId||!data.title)throw new Error('planId и title обязательны.');var l=_esLoc_(data,s),r={item_id:generateId_('EXECUTION_ITEMS'),execution_plan_id:data.planId,organization_id:s.organization_id,location_id:l,source_type:String(data.sourceType||'MANUAL'),source_id:String(data.sourceId||''),title:String(data.title).slice(0,200),priority:String(data.priority||'MEDIUM'),owner_role:String(data.ownerRole||'МЕНЕДЖЕР'),owner_id:String(data.ownerId||''),due_at:String(data.dueAt||''),status:'OPEN',dependency_json:JSON.stringify(data.dependencies||[]),evidence_json:'',created_by:s.user_id,created_at:nowIso_(),completed_at:''};insertRow_('EXECUTION_ITEMS',r);return r;}
function getExecutionPlan_(data,s){data=data||{};var l=_esLoc_(data,s),plans=_esRows_('EXECUTION_PLANS',function(r){return _esScope_(r,{organization_id:s.organization_id,location_id:l})&&(!data.status||r.status===data.status);},STAGE49_LIMIT_);plans.forEach(function(p){p.items=_esRows_('EXECUTION_ITEMS',function(i){return i.execution_plan_id===p.execution_plan_id&&_esScope_(i,{organization_id:s.organization_id,location_id:l});},STAGE49_LIMIT_);});return plans;}

// Stage 50 — единый enterprise command snapshot.
function getEnterpriseCommandCenter_(data,s){data=data||{};var l=_esLoc_(data,s),p=_esPeriod_(data),cock=getComplianceCockpit_(data,s),cap=getWorkforceCapacity_(data,s),capacity=getCapacityOverview_(data,s),signals=getInventorySignals_(data,s),actions=getManagementActions42_({locationId:l},s),vars=getKpiVariances_({locationId:l,limit:STAGE50_LIMIT_},s);var blocked=(cock&&cock.status==='BLOCKED')||capacity.status==='BLOCKED',attention=(cock&&cock.status==='ATTENTION')||cap.status==='ATTENTION'||signals.items.some(function(x){return x.status==='SHORTAGE';})||vars.some(function(x){return x.status==='OFF_TARGET';});return {period:p,location_id:l,status:blocked?'BLOCKED':(attention?'ATTENTION':'GREEN'),compliance:cock,workforce:cap,production_capacity:capacity,inventory_signals:signals,management_actions:actions.slice(0,100),kpi_variances:vars.slice(0,100),generated_at:nowIso_()};}
function enterpriseExecutionStage42to50Trigger_(){try{getOrganizations_(null).forEach(function(org){try{(getLocations_(org.organization_id)||[]).forEach(function(loc){var s={user_id:'system',organization_id:org.organization_id,location_id:loc.location_id,role:'ADMIN',allowed_locations:[loc.location_id],cascade_id:'',operation_id:''};orchestrateManagementActions42_({locationId:loc.location_id},s);var cc=getEnterpriseCommandCenter_({locationId:loc.location_id},s);if(cc.status!=='GREEN')notify_(org.organization_id,loc.location_id,'ENTERPRISE_COMMAND_CENTER','Command Center: '+cc.status,'ec4250|'+loc.location_id+'|'+cc.period.from);});}catch(e){logSystemError_('enterpriseExecutionStage42to50Trigger_',org.organization_id,'enterprise_42_50',e);}});}catch(e){logSystemError_('enterpriseExecutionStage42to50Trigger_',null,'enterprise_42_50',e);}}
function enterpriseStages42to50Tests_(){var o=[];function ok(n,c,d){o.push({name:n,status:c?'OK':'FAIL',detail:d||''});}ok('42_ACTIONS',typeof createManagementAction_==='function'&&typeof orchestrateManagementActions42_==='function');ok('43_WORKFORCE',typeof createWorkforcePlan_==='function'&&typeof getWorkforceCapacity_==='function');ok('44_SUPPLIERS',typeof runSupplierScorecards_==='function');ok('45_INVENTORY',typeof createInventoryPolicy_==='function'&&typeof getInventorySignals_==='function');ok('46_CAPACITY',typeof createCapacityPlan_==='function'&&typeof getCapacityOverview_==='function');ok('47_MENU',typeof getMenuEngineering_==='function');ok('48_SCENARIO',typeof createScenarioPlan_==='function'&&typeof runScenario_==='function');ok('49_EXECUTION',typeof createExecutionPlan_==='function'&&typeof addExecutionItem_==='function');ok('50_COMMAND',typeof getEnterpriseCommandCenter_==='function');ok('SCOPE',_esScope_({organization_id:'A',location_id:'L'},{organization_id:'A',location_id:'L'}));ok('PERIOD',_esPeriod_({dateFrom:'2026-01-01',dateTo:'2026-01-31'}).to==='2026-01-31');ok('NUM',_esNum_('3.5')===3.5);return o;}
