/**
 * CORE100 Stage 51-60 — Digital Factory Layer.
 * Read/write only through controlled APIs; no automatic stock, finance or production postings.
 */
var STAGE51_60_LIMIT_ = 500;
function _dfRows_(sheet, predicate, limit){
  var rows = getSheetData_(sheet) || [];
  var out=[]; for(var i=0;i<rows.length && out.length<(limit||STAGE51_60_LIMIT_);i++){ if(!predicate || predicate(rows[i])) out.push(rows[i]); }
  return out;
}
function _dfScope_(r,s){ return String(r.organization_id||'')===String(s.organization_id||'') && (!r.location_id || !s.location_id || String(r.location_id)===String(s.location_id)); }
function _dfLoc_(d,s){ return String((d&&d.locationId)||s.location_id||''); }
function _dfNum_(v){ var n=Number(v); return isFinite(n)?n:0; }
function _dfDate_(d){ return String(d||new Date().toISOString().slice(0,10)).slice(0,10); }
function _dfId_(prefix){ return generateId_(prefix); }

// 51 — Shift Dispatcher
function createShiftPlan51_(d,s){ d=d||{}; var loc=_dfLoc_(d,s), date=_dfDate_(d.date), r={shift_plan_id:_dfId_('SHP'),organization_id:s.organization_id,location_id:loc,date:date,shift_code:String(d.shiftCode||'DAY'),workshop_id:String(d.workshopId||''),planned_hours:_dfNum_(d.plannedHours),status:'DRAFT',owner_id:String(d.ownerId||''),created_by:s.user_id,created_at:nowIso_()}; if(r.planned_hours<0) throw new Error('plannedHours не может быть отрицательным.'); insertRow_('SHIFT_PLANS',r); return r; }
function getShiftPlans51_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),date=d.date; return _dfRows_('SHIFT_PLANS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&(!date||r.date===date)&&(!d.status||r.status===d.status);}); }
function createShiftAssignment51_(d,s){ d=d||{}; var loc=_dfLoc_(d,s); var r={assignment_id:_dfId_('SHA'),shift_plan_id:String(d.shiftPlanId||''),organization_id:s.organization_id,location_id:loc,employee_id:String(d.employeeId||''),role:String(d.role||''),planned_hours:_dfNum_(d.plannedHours),status:'PLANNED',created_by:s.user_id,created_at:nowIso_()}; if(!r.shift_plan_id||!r.employee_id) throw new Error('shiftPlanId и employeeId обязательны.'); insertRow_('SHIFT_ASSIGNMENTS',r); return r; }
function getShiftDispatcher51_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),date=d.date||_dfDate_(); var plans=getShiftPlans51_({locationId:loc,date:date},s); var a=_dfRows_('SHIFT_ASSIGNMENTS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&plans.some(function(p){return p.shift_plan_id===r.shift_plan_id;});}); var planned=plans.reduce(function(x,p){return x+_dfNum_(p.planned_hours);},0), assigned=a.reduce(function(x,p){return x+_dfNum_(p.planned_hours);},0); return {date:date,location_id:loc,plans:plans,assignments:a,planned_hours:planned,assigned_hours:assigned,gap_hours:Math.max(0,planned-assigned),status:assigned>planned?'OVERALLOCATED':(assigned<planned?'UNDERSTAFFED':'BALANCED')}; }

// 52 — Workforce productivity
function getLaborProductivity52_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),from=_dfDate_(d.dateFrom),to=_dfDate_(d.dateTo),prod=_dfRows_('PRODUCTION',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&String(r.дата||r.date||'').slice(0,10)>=from&&String(r.дата||r.date||'').slice(0,10)<=to;}); var hours=_dfRows_('SHIFT_ASSIGNMENTS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc});}).reduce(function(x,r){return x+_dfNum_(r.planned_hours);},0); var qty=prod.reduce(function(x,r){return x+_dfNum_(r.количество||r.qty);},0); return {date_from:from,date_to:to,production_rows:prod.length,output_qty:qty,planned_labor_hours:hours,output_per_hour:hours?qty/hours:0}; }

// 53 — Procurement cycle
function getProcurementCycle53_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),req=_dfRows_('PURCHASE_REQUESTS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc});}); var now=Date.now(),open=req.filter(function(r){return !['CLOSED','COMPLETED','RECEIVED','CANCELLED'].includes(String(r.status||'').toUpperCase());}); var overdue=open.filter(function(r){return r.due_at && new Date(r.due_at).getTime()<now;}); return {location_id:loc,total:req.length,open:open.length,overdue:overdue.length,overdue_items:overdue.slice(0,100)}; }
function createProcurementCycleAction53_(d,s){ return createManagementAction_({locationId:_dfLoc_(d,s),sourceType:'PROCUREMENT_CYCLE',sourceId:String(d.sourceId||''),title:d.title||'Закрыть закупочный цикл',description:d.description||'',priority:d.priority||'HIGH',ownerRole:d.ownerRole||'МЕНЕДЖЕР',dueAt:d.dueAt||''},s); }

// 54 — Workshop performance
function getWorkshopPerformance54_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),from=_dfDate_(d.dateFrom),to=_dfDate_(d.dateTo),rows=_dfRows_('PRODUCTION',function(r){var dt=String(r.дата||r.date||'').slice(0,10);return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&dt>=from&&dt<=to;}); var by={}; rows.forEach(function(r){var w=String(r.workshop_id||'UNASSIGNED');if(!by[w])by[w]={workshop_id:w,operations:0,qty:0};by[w].operations++;by[w].qty+=_dfNum_(r.количество||r.qty);}); return {date_from:from,date_to:to,workshops:Object.keys(by).map(function(k){return by[k];})}; }

// 55 — Production calendar
function createProductionCalendar55_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),r={calendar_id:_dfId_('PCAL'),organization_id:s.organization_id,location_id:loc,date_from:_dfDate_(d.dateFrom),date_to:_dfDate_(d.dateTo),name:String(d.name||'Производственный календарь'),status:'DRAFT',created_by:s.user_id,created_at:nowIso_()}; insertRow_('PRODUCTION_CALENDARS',r); return r; }
function addProductionCalendarItem55_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),r={item_id:_dfId_('PCALI'),calendar_id:String(d.calendarId||''),organization_id:s.organization_id,location_id:loc,date:_dfDate_(d.date),workshop_id:String(d.workshopId||''),production_plan_id:String(d.productionPlanId||''),planned_qty:_dfNum_(d.plannedQty),priority:String(d.priority||'MEDIUM'),status:'PLANNED',created_by:s.user_id,created_at:nowIso_()}; if(!r.calendar_id)throw new Error('calendarId обязателен.'); insertRow_('PRODUCTION_CALENDAR_ITEMS',r); return r; }
function getProductionCalendar55_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),c=_dfRows_('PRODUCTION_CALENDARS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&(!d.status||r.status===d.status);}); var ids=c.map(function(x){return x.calendar_id;}); var items=_dfRows_('PRODUCTION_CALENDAR_ITEMS',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc})&&ids.indexOf(r.calendar_id)>=0;}); return {calendars:c,items:items}; }

// 56 — Unit economics
function getUnitEconomics56_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),sales=_dfRows_('SALES',function(r){return _dfScope_(r,{organization_id:s.organization_id,location_id:loc});}),by={}; sales.forEach(function(r){var dish=String(r.dish_id||'UNASSIGNED');if(!by[dish])by[dish]={dish_id:dish,qty:0,revenue:0};by[dish].qty+=_dfNum_(r.qty);by[dish].revenue+=_dfNum_(r.сумма||r.amount||r.qty*r.цена_продажи);}); return Object.keys(by).map(function(k){var x=by[k];x.avg_price=x.qty?x.revenue/x.qty:0;return x;}); }

// 57 — Digital twin snapshot
function getDigitalTwin57_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),cc=getEnterpriseCommandCenter_({locationId:loc},s),disp=getShiftDispatcher51_({locationId:loc,date:d.date},s),proc=getProcurementCycle53_({locationId:loc},s),wp=getWorkshopPerformance54_({locationId:loc,dateFrom:d.dateFrom,dateTo:d.dateTo},s); return {generated_at:nowIso_(),location_id:loc,status:cc.status,command_center:cc,shift_dispatcher:disp,procurement:proc,workshops:wp}; }

// 58 — Scenario execution bridge
function runExecutionScenario58_(d,s){ d=d||{}; var scenario=runScenario_(d,s); return {scenario:scenario,simulation_only:true,mutations:[]}; }

// 59 — Operational alerts
function getOperationalAlerts59_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),alerts=[]; var disp=getShiftDispatcher51_({locationId:loc,date:d.date},s); if(disp.status==='UNDERSTAFFED')alerts.push({code:'SHIFT_UNDERSTAFFED',severity:'HIGH',message:'Недостаточно назначенных часов смены.',gap_hours:disp.gap_hours}); if(disp.status==='OVERALLOCATED')alerts.push({code:'SHIFT_OVERALLOCATED',severity:'HIGH',message:'Назначено больше часов, чем план.',gap_hours:disp.gap_hours}); var pc=getProcurementCycle53_({locationId:loc},s); if(pc.overdue)alerts.push({code:'PROCUREMENT_OVERDUE',severity:'HIGH',message:'Просрочены закупочные запросы.',count:pc.overdue}); var cc=getEnterpriseCommandCenter_({locationId:loc},s); if(cc.status!=='GREEN')alerts.push({code:'ENTERPRISE_STATUS',severity:cc.status==='BLOCKED'?'CRITICAL':'HIGH',message:'Enterprise Command Center: '+cc.status}); return alerts; }

// 60 — Digital Factory Command Center
function getDigitalFactoryCommandCenter60_(d,s){ d=d||{}; var loc=_dfLoc_(d,s),alerts=getOperationalAlerts59_({locationId:loc,date:d.date},s),twin=getDigitalTwin57_({locationId:loc,date:d.date,dateFrom:d.dateFrom,dateTo:d.dateTo},s),labor=getLaborProductivity52_({locationId:loc,dateFrom:d.dateFrom,dateTo:d.dateTo},s),unit=getUnitEconomics56_({locationId:loc},s); var status=alerts.some(function(a){return a.severity==='CRITICAL';})?'BLOCKED':(alerts.length?'ATTENTION':'GREEN'); return {status:status,generated_at:nowIso_(),location_id:loc,alerts:alerts,digital_twin:twin,labor_productivity:labor,unit_economics:unit.slice(0,200)}; }

function digitalFactoryStage51to60Trigger_(){ try{ getOrganizations_(null).forEach(function(org){ try{ (getLocations_(org.organization_id)||[]).forEach(function(loc){ var s={user_id:'system',organization_id:org.organization_id,location_id:loc.location_id,role:'ADMIN',allowed_locations:[loc.location_id],cascade_id:'',operation_id:''}; var cc=getDigitalFactoryCommandCenter60_({locationId:loc.location_id},s); if(cc.status!=='GREEN') notify_(org.organization_id,loc.location_id,'DIGITAL_FACTORY_COMMAND_CENTER','Digital Factory: '+cc.status,'df5160|'+loc.location_id); }); }catch(e){logSystemError_('digitalFactoryStage51to60Trigger_',org.organization_id,'digital_factory_51_60',e);} }); }catch(e){logSystemError_('digitalFactoryStage51to60Trigger_',null,'digital_factory_51_60',e);} }
function digitalFactoryStage51to60Tests_(){var o=[];function ok(n,c,d){o.push({name:n,status:c?'OK':'FAIL',detail:d||''});}ok('51_SHIFT',typeof createShiftPlan51_==='function'&&typeof getShiftDispatcher51_==='function');ok('52_LABOR',typeof getLaborProductivity52_==='function');ok('53_PROCUREMENT',typeof getProcurementCycle53_==='function');ok('54_WORKSHOP',typeof getWorkshopPerformance54_==='function');ok('55_CALENDAR',typeof createProductionCalendar55_==='function'&&typeof addProductionCalendarItem55_==='function');ok('56_UNIT_ECONOMICS',typeof getUnitEconomics56_==='function');ok('57_TWIN',typeof getDigitalTwin57_==='function');ok('58_SCENARIO',typeof runExecutionScenario58_==='function');ok('59_ALERTS',typeof getOperationalAlerts59_==='function');ok('60_COMMAND',typeof getDigitalFactoryCommandCenter60_==='function');ok('SCOPE',_dfScope_({organization_id:'A',location_id:'L'},{organization_id:'A',location_id:'L'}));ok('NUM',_dfNum_('4.2')===4.2);return o;}
