/**
 * ЦЕХ — Stage 41: KPI Targets & Variance Management.
 * Управленческие цели, отклонения и actions. Не являются бухгалтерскими нормативами.
 */
var KPI41_LIMIT_=500;
var KPI41_METRICS_={
  revenue:{title:'Выручка',direction:'MIN',source:'headline.revenue',unit:'money'},
  gross_margin_pct:{title:'Валовая маржа',direction:'MIN',source:'headline.gross_margin_pct',unit:'pct'},
  prime_cost_pct:{title:'Prime Cost',direction:'MAX',source:'headline.prime_cost_pct',unit:'pct'},
  operating_profit:{title:'Операционная прибыль',direction:'MIN',source:'headline.operating_profit',unit:'money'},
  cash_net:{title:'Net Cash Flow',direction:'MIN',source:'headline.cash_net',unit:'money'},
  writeoffs:{title:'Списания',direction:'MAX',source:'sections.LOSSES.payload.списания.сумма',unit:'money'},
  compliance_score:{title:'Compliance coverage',direction:'MIN',source:'sections.COMPLIANCE.payload.scorecard.control_coverage_pct',unit:'pct'}
};
function _k41Scope_(r,s){return !!r&&r.organization_id===s.organization_id&&(!s.location_id||!r.location_id||r.location_id===s.location_id);}
function _k41Date_(v){return String(v||'').slice(0,10);}
function _k41Num_(v){var n=Number(v);return isNaN(n)?0:n;}
function _k41Path_(obj,path){return String(path||'').split('.').reduce(function(a,k){return a==null?null:a[k];},obj);}
function _k41Period_(data){var from=_k41Date_(data.dateFrom),to=_k41Date_(data.dateTo);if(from||to){if(!from||!to||to<from)throw new Error('Неверный период KPI.');return {from:from,to:to};}var d=new Date();d.setUTCDate(1);d.setUTCDate(d.getUTCDate()-1);var to2=d.toISOString().slice(0,10);d.setUTCDate(1);return {from:d.toISOString().slice(0,10),to:to2};}
function _k41Pack_(data,s){return getEnterpriseBoardPack_(data,s).pack;}
function _k41Variance_(actual,target,direction,tol){actual=_k41Num_(actual);target=_k41Num_(target);tol=_k41Num_(tol);var delta=actual-target,pass=direction==='MAX'?actual<=target+tol:actual>=target-tol;var pct=target?delta/Math.abs(target)*100:null;return {actual:actual,target:target,delta:delta,delta_pct:pct,pass:pass,status:pass?'ON_TARGET':'OFF_TARGET'};}
function getKpiMetricCatalog_(session){return Object.keys(KPI41_METRICS_).map(function(k){var x=KPI41_METRICS_[k];return {code:k,title:x.title,direction:x.direction,unit:x.unit,source:x.source};});}
function getKpiTargets_(data,session){data=data||{};var loc=data.locationId||session.location_id||'';if(loc)assertLocationAllowed_(session,loc,'LOCATIONS:'+loc);return findRows_('KPI_TARGETS',function(r){return _k41Scope_(r,{organization_id:session.organization_id,location_id:loc})&&(!data.metricCode||r.metric_code===data.metricCode)&&(!data.status||r.status===data.status)&&(!data.period_from||String(r.period_from)<=String(data.period_from))&&(!data.period_to||String(r.period_to)>=String(data.period_to));}).slice(0,KPI41_LIMIT_);}
function createKpiTarget_(data,session){data=data||{};var metric=KPI41_METRICS_[data.metricCode];if(!metric)throw new Error('Неизвестный KPI metricCode.');var from=_k41Date_(data.periodFrom),to=_k41Date_(data.periodTo);if(!from||!to||to<from)throw new Error('Нужен корректный период KPI target.');var target=Number(data.target);if(!isFinite(target))throw new Error('target должен быть числом.');var loc=data.locationId||session.location_id||'';if(loc)assertLocationAllowed_(session,loc,'LOCATIONS:'+loc);var active=findRows_('KPI_TARGETS',function(r){return _k41Scope_(r,{organization_id:session.organization_id,location_id:loc})&&r.metric_code===data.metricCode&&String(r.status)==='ACTIVE'&&String(r.period_from)<=to&&String(r.period_to)>=from;});if(active.length)throw new Error('Для KPI уже существует пересекающийся ACTIVE target.');var row={target_id:generateId_('KPI_TARGETS'),organization_id:session.organization_id,location_id:loc,metric_code:data.metricCode,metric_title:metric.title,direction:data.direction||metric.direction,target_value:target,tolerance:Number(data.tolerance||0),period_from:from,period_to:to,status:data.status||'ACTIVE',owner_role:data.ownerRole||'ДИРЕКТОР',owner_id:data.ownerId||'',note:String(data.note||'').slice(0,1000),created_by:session.user_id,created_at:nowIso_(),updated_at:nowIso_()};insertRow_('KPI_TARGETS',row);auditLog_(session.user_id,'Создан KPI target','KPI_TARGETS:'+row.target_id,'',JSON.stringify(row),'success',session.cascade_id||'');return row;}
function runKpiVariance_(data,session){data=data||{};var p=_k41Period_(data),loc=data.locationId||session.location_id||'';if(loc)assertLocationAllowed_(session,loc,'LOCATIONS:'+loc);var pack=_k41Pack_({dateFrom:p.from,dateTo:p.to,locationId:loc},session),targets=getKpiTargets_({locationId:loc,status:'ACTIVE'},session),out=[],packId=data.boardPackId||'';targets.forEach(function(t){if(String(t.period_from)>p.to||String(t.period_to)<p.from)return;var metric=KPI41_METRICS_[t.metric_code];if(!metric)return;var actual=_k41Path_(pack,metric.source);var v=_k41Variance_(actual,t.target_value,t.direction||metric.direction,t.tolerance);var existing=findRows_('KPI_VARIANCES',function(x){return x.target_id===t.target_id&&x.date_from===p.from&&x.date_to===p.to&&_k41Scope_(x,{organization_id:session.organization_id,location_id:loc});});if(existing.length){out.push(existing[0]);return;}var row={variance_id:generateId_('KPI_VARIANCES'),organization_id:session.organization_id,location_id:loc,period:p.from.slice(0,7),date_from:p.from,date_to:p.to,target_id:t.target_id,metric_code:t.metric_code,actual_value:_k41Num_(v.actual),target_value:_k41Num_(v.target),delta:_k41Num_(v.delta),delta_pct:v.delta_pct==null?'':v.delta_pct,status:v.status,board_pack_id:packId,generated_by:session.user_id,generated_at:nowIso_(),created_at:nowIso_()};insertRow_('KPI_VARIANCES',row);out.push(row);});return {period:p,status:out.some(function(x){return x.status==='OFF_TARGET';})?'ATTENTION':'GREEN',items:out};}
function getKpiVariances_(data,session){data=data||{};var loc=data.locationId||session.location_id||'';if(loc)assertLocationAllowed_(session,loc,'LOCATIONS:'+loc);return findRows_('KPI_VARIANCES',function(r){return _k41Scope_(r,{organization_id:session.organization_id,location_id:loc})&&(!data.period||r.period===data.period)&&(!data.metricCode||r.metric_code===data.metricCode)&&(!data.status||r.status===data.status);}).sort(function(a,b){return String(b.generated_at||'').localeCompare(String(a.generated_at||''));}).slice(0,Math.min(KPI41_LIMIT_,Number(data.limit)||100));}
function createKpiAction_(data,session){data=data||{};if(!data.varianceId)throw new Error('varianceId обязателен.');var vars=getKpiVariances_({locationId:data.locationId||session.location_id||'',limit:KPI41_LIMIT_},session).filter(function(r){return r.variance_id===data.varianceId;});if(!vars.length)throw new Error('Отклонение KPI не найдено.');var v=vars[0],loc=v.location_id||session.location_id||'';var row={action_id:generateId_('KPI_ACTIONS'),variance_id:v.variance_id,organization_id:session.organization_id,location_id:loc,title:String(data.title||('Корректирующее действие: '+v.metric_code)).slice(0,200),description:String(data.description||'').slice(0,2000),responsible_role:data.responsibleRole||'ДИРЕКТОР',responsible_id:data.responsibleId||'',due_at:String(data.dueAt||''),status:'OPEN',created_by:session.user_id,created_at:nowIso_(),completed_by:'',completed_at:'',evidence_json:'',updated_at:nowIso_()};insertRow_('KPI_ACTIONS',row);auditLog_(session.user_id,'Создано KPI action','KPI_ACTIONS:'+row.action_id,'',JSON.stringify(row),'success',session.cascade_id||'');return row;}
function completeKpiAction_(data,session){data=data||{};var id=data.actionId;if(!id)throw new Error('actionId обязателен.');var rows=findRows_('KPI_ACTIONS',function(r){return r.action_id===id&&_k41Scope_(r,{organization_id:session.organization_id,location_id:data.locationId||session.location_id||''});});if(!rows.length)throw new Error('KPI action не найден.');var r=rows[0];if(r.status==='CLOSED')return r;r.status='CLOSED';r.completed_by=session.user_id;r.completed_at=nowIso_();r.evidence_json=JSON.stringify(data.evidence||{});r.updated_at=nowIso_();updateRow_('KPI_ACTIONS',r);auditLog_(session.user_id,'Закрыто KPI action','KPI_ACTIONS:'+r.action_id,'',JSON.stringify({evidence:data.evidence||{}}),'success',session.cascade_id||'');return r;}
function getKpiActions_(data,session){data=data||{};var loc=data.locationId||session.location_id||'';if(loc)assertLocationAllowed_(session,loc,'LOCATIONS:'+loc);return findRows_('KPI_ACTIONS',function(r){return _k41Scope_(r,{organization_id:session.organization_id,location_id:loc})&&(!data.status||r.status===data.status)&&(!data.varianceId||r.variance_id===data.varianceId);}).sort(function(a,b){return String(b.created_at||'').localeCompare(String(a.created_at||''));}).slice(0,Math.min(KPI41_LIMIT_,Number(data.limit)||100));}
function kpiTargetsStage41Trigger_(){try{getOrganizations_(null).forEach(function(org){try{var locs=getLocations_(org.organization_id)||[];locs.forEach(function(loc){var s={user_id:'system',organization_id:org.organization_id,location_id:loc.location_id,role:'ADMIN',allowed_locations:[loc.location_id],cascade_id:'',operation_id:''};var r=runKpiVariance_({locationId:loc.location_id},s);if(r.status==='ATTENTION')notify_(org.organization_id,loc.location_id,'KPI_VARIANCE','Есть отклонения KPI за '+r.period.from+'—'+r.period.to,'kpi41|'+loc.location_id+'|'+r.period.from);});}catch(e){logSystemError_('kpiTargetsStage41Trigger_',org.organization_id,'kpi_targets',e);}});}catch(e){logSystemError_('kpiTargetsStage41Trigger_',null,'kpi_targets',e);}}
function kpiTargetsStage41Tests_(){var o=[];function ok(n,c,d){o.push({name:n,status:c?'OK':'FAIL',detail:d||''});}ok('CATALOG',Object.keys(KPI41_METRICS_).length===7);ok('TARGET_API',typeof createKpiTarget_==='function'&&typeof getKpiTargets_==='function');ok('VARIANCE_API',typeof runKpiVariance_==='function'&&typeof getKpiVariances_==='function');ok('ACTION_API',typeof createKpiAction_==='function'&&typeof completeKpiAction_==='function');ok('PATH',_k41Path_({a:{b:3}},'a.b')===3);ok('DIRECTION',_k41Variance_(5,4,'MIN',0).pass&&_k41Variance_(5,4,'MAX',0).pass===false);ok('LIMIT',KPI41_LIMIT_===500);return o;}
